site_name: ğŸ‘¾ DESMA126 Game Engine
theme: 
  name: simple-blog
  components:
    title: false
  theme_style: light
extra_css:
  - extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js
  - javascripts/config.js
nav:
  - ğŸ  Home: index.md
  - ğŸ“œ Syllabus: syllabus.md
  - ğŸ“… Schedule: schedule.md
  - ğŸ“Œ Assignments:
    - How To Submit: how-to-submit.md
    - Readings & Homeplays: readings-and-homeplays.md
    - Project 1: project-1.md
    - Project 2: project-2.md
    - Project 3: project-3.md